### ISSUE TITLE
Invalid Grunt task bower_components directory path

### ISSUE THREAD

**Issue by remluben** [gilbarbara/generator-web#1]
I have used the generator for the first time and encountered an issue concerning tasks working with bower packages:
- dist/bootstrap.min.css
- dist/font-awesome/css/font-awesome.min.css

are not available after running <code>grunt build</code>

<i>dist/extensions.min.js</i> is always empty as the specified bootstrap JS file location seems to be invalid.

After I added the <i>app/</i> path to the <i>bower_components/..</i> paths within the <i>Gruntfile.js</i> everything seemed to work okay so far.

Have you also encountered this issue?

**Comment by gilbarbara** [comment]
hey,

I just tried to scaffold a new directory and grunt built as expected.
I don't use the app/ path in the generator, maybe it is a .bowerrc directive?

**Comment by remluben** [comment]
Yes, you are completely right. I must have messed it up. Within the project directory, there exists a .bowerrc file which specifies the <i>app/bower_components</i> directory.

I did not manage to reproduce this error, when creating a fresh new directory and using your generator, so I will close this issue.
