### ISSUE TITLE
UNMET PEER DEPENDENCY yo@>=1.1.2

### ISSUE THREAD

**Issue by kikeonline** [gilbarbara/generator-web#5]
UNMET PEER DEPENDENCY yo@>=1.1.2

npm WARN EPEERINVALID generator-web@0.2.5 requires a peer of yo@>=1.1.2 but none was installed.

**Comment by gilbarbara** [comment]
hey, `Peer Dependencies` means that this generator expects `yo` to be installed but it won't install itself to avoid duplication.
Just `npm install -g yo`
